Fix scoping error that caused stack trace
MSP-11489

When cracking an NTLM hash with an existing Login,
Creation#create_cracked_credential would fail with:

  NameError undefined local variable or method `core'